[tool.poetry]
name = "perf-llm-eval"
version = "0.1.0"
description = ""
authors = ["Samuel Monson <smonson@redhat.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
lm-eval = {extras = ["api"], version = "0.4.5"}
unitxt = "^1.13.1"


[tool.poetry.scripts]
perf-llm-eval = "perf_llm_eval.__main__:eval_cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
